name: VShulkers
version: '${project.version}'
main: org.txtox8729.vshulkers.VShulkers
api-version: '1.16'
author: [ Tox_8729 ]
softdepend: [Essentials]

permissions:
  vshulker.admin:
    description: Право для перезагрузки плагина
    default: op
  vshulker.bypass:
    description: Право для переноса шалкеров в эндер сундуке и тд....
    default: op
  vshulker.limit:
    description: Право для обхода ограничений шалкеров
    default: op

commands:
  vshulker:
    description: Команда для перезагрузки плагина
