name: VShulkers
version: '${project.version}'
main: org.txtox8729.vshulkers.VShulkers
api-version: '1.16'
author: [ Tox_8729 ]
softdepend: [Essentials]

commands:
  vshulker:

permissions:
  vshulker.admin:
    default: op
  vshulker.bypass:
    default: op
  vshulker.limit:
    default: op
  vshulker.mode.bypass:
    default: op
